config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :band, :band_id, :live, presence: true

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album
    
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true

  after_initialize :session_token

  # before running any validation run this method:
  # if user doesn't have any session token, our validations will fail
  # as we validate :session_token
  before_validation :ensure_session_token

  # returns a random session token.
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    # first, find if any users exists in our DB with the provided email.
    user = User.find_by(email: email)

    # if user exists, return the user, else return nil.
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    # assigning a new session token
    self.session_token = User.generate_session_token

    # save the user with the new session token
    self.save!
    self.session_token
  end

  def ensure_session_token
    # make sure the user has a session token
    # do nothing if they already have a session token
    # using lazy assignement:
    self.session_token ||= User.generate_session_token

    # WHY DON'T WE SAVE USER HERE?
  end

  def password=(password)
    # set the encrypted hash using BCrypt
    self.password_digest = BCrypt::Password.create(password)

    # we need the @password instance variable to validate
    @password = password
  end

  def is_password?(password)
    # Check if user's encrypted hash matches the Bcrypted password.
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # before_action :require_user!

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :live, :title, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :band

  def band
    @band ||= Band.find(params[:id])
  end

  def current_user
    # If @current_user does not exist, check the user by session_token
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    # if current_user do exist, this will return true
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  #this is only for finding the band and rendering the edit .erb
  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to 
    end
  end

  def destroy
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Invalid credentials']
      render :new
      # redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def show
    render :show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<center><h2>Add a new album</h2></center>

<form action="<%= albums_url %>" method="post">
  <label>Title:
    <input type="text" name="album[title]">
  </label>
  <br>
  <br>
  <label>Band:
    <select name="album[band_id]">
      <% Band.all.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
      <% end %>
    </select>
  </label>
  <br>
  <br>
  <label>Live</label>
  <input type="radio" id="post_category_rails" name="album[live]" value="true" checked="checked" />

  <label>Studio</label>
  <input type="radio" id="post_category_java" name="album[live]" value="false" />
  <br>
  <br>
  <label>Year:
      <input type="number" name="album[year]">
  </label>
  <br>
  <br>
  <input type="submit" value="Submit Album">
</form>

app/views/albums/show.html.erb
<h1> Album Details </h1>

<ul>
  

</ul>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Band Name:
  <input type="text" name="band[name]" value="<%= band.name %>"> 
  </label>

  <input type="submit" value="Add Band!">
</form>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>Add new Band</h1>

<form action="<%= bands_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Band Name:
  <input type="text" name="band[name]"> 
  </label>

  <input type="submit" value="Add Band!">
</form>

app/views/bands/show.html.erb
<h1> Band Profile </h1>

Band Name: 
<%= band.name %>
<br>
Albums:
<ul>
<% band.albums.each do |album| %>
  <li>
    <%= album.title %>
  </li>
</ul>
<% end %>
<br>


<% if band.name = 'Metallica' %>
<img src = "https://thumbs.gfycat.com/UnfortunateRashAfricanfisheagle-small.gif" />
<% end %>

<br>
<a href="<%= edit_band_url(@band) %>">Edit this Band</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <center><h1>The Music App Salutes You!</h1></center>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>SIGN UP</h1>

<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Email:
    <input type="text" name="user[email]">
  </label>
  <br>
  <label>Password:
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>